= Shopping Cart Service Guide
Matthew Sagala;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[introduction]
= Introduction

SPI Microservice is a backend system that process the flow of data from EQ Interface to Third Party Service providers.
[getting-started]
= Getting started


[getting-started-running-the-service]
== Running the service
SPI Microservice is written using http://projects.spring.io/spring-boot[Spring Boot] which
makes it easy to get it up and running so that you can start exploring the REST API.

The first step is to clone the Git repository:

[source,bash]
----
$ git clone git@bitbucket.org:ascendcorp/ami-ph-eq-spi
----

Once the clone is complete, you're ready to get the service up and running:

[source,bash]
----
$ cd ami-ph-eq-spi
$ mvn clean package
$ java -jar target/*.jar
----

= Aggregators Services

== Billspay

=== Billspay Bayadcenter
Post-Payment Request
include::bayadcenter-postpayment/curl-request.adoc[]
Post-Payment Response
include::bayadcenter-postpayment/http-response.adoc[]

=== Billspay ECPAY
Pre-Order Request
include::ecpay-preorder/curl-request.adoc[]
Pre-Order Response
include::ecpay-preorder/http-response.adoc[]

Post-Payment Request
include::ecpay-postpayment/curl-request.adoc[]
Post-Payment Response
include::ecpay-postpayment/http-response.adoc[]

=== Billspay Paynamics
Pre-Order Request
include::paynamics-preorder/curl-request.adoc[]
Pre-Order Response
include::paynamics-preorder/http-response.adoc[]

Post-Payment Request
include::paynamics-postpayment/curl-request.adoc[]
Post-Payment Response
include::paynamics-postpayment/http-response.adoc[]